import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const hello = trpc.useQuery(['hello', { text: 'Dan' }]);

  if (!hello.data) return <p>...Loading</p>;

  return (
    <div>
      <Head>
        <title>Team Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className='text-center text-xl font-bold'>Team Builder</h2>
        <p>from api: {hello.data.msg}</p>
      </main>
    </div>
  );
}

export default Home;
