import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useForm } from 'react-hook-form';
import { ISignUp, signUpSchema } from "../utils/validation/auth";
import { zodResolver } from '@hookform/resolvers/zod';
import { trpc } from "../utils/trpc";
import { useCallback } from "react";

const SignUp: NextPage = () => {
  const router = useRouter();
  const { register, handleSubmit } = useForm<ISignUp>({
    resolver: zodResolver(signUpSchema)
  });

  const { mutateAsync } = trpc.useMutation(['signup']);

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      const result = await mutateAsync(data);
      if (result.status === 201) {
        router.push('/');
      }
    }, 
    [mutateAsync, router]
  );

  return (
    <div>
      <Head>
        <title>Team Builder - Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form 
          onSubmit={handleSubmit(onSubmit)}
          className="bg-slate-200 flex items-center justify-center h-screen w-full"
        >
          <div className="bg-slate-300 w-96 shadow-xl rounded-lg p-5 space-y-5">
            <h2 className="text-2xl">Create an account</h2>
            <input 
              type="text" 
              placeholder="Username"
              className="w-full p-3 rounded" 
              {...register("username")}
            />
            <input 
              type="email" 
              placeholder="Email"
              className="w-full p-3 rounded" 
              {...register('email')}
            />
            <input 
              type="password" 
              placeholder="Password"
              className="w-full p-3 rounded" 
              {...register('password')}
            />
            <div className="flex justify-between">
              <Link href='/'>
                <button className="w-[48%] py-3 border-2 border-green-200 rounded">
                  Go to login
                </button>
              </Link>
              <button 
                className="w-[48%] bg-green-200 border-2 border-green-200 rounded py-3"
                type="submit"
                onSubmit={() => onSubmit}
              >
                Sign up
              </button>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}

export default SignUp;